# Generated by Django 2.2.24 on 2024-08-02 16:42

from django.db import migrations


def fill_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(name=flat.owner)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20240802_1929'),
    ]

    operations = [
        migrations.RunPython(fill_owner),
    ]
