# Generated by Django 2.2.24 on 2024-08-04 05:05

from django.db import migrations


def fill_owner_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all():
        flats = Flat.objects.filter(owner=owner.name)
        owner.flats.set(flats)




class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20240804_0805'),
    ]

    operations = [
        migrations.RunPython(fill_owner_flats),
    ]
