# Generated by Django 2.2.24 on 2024-08-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_auto_20240805_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='flats',
            field=models.ManyToManyField(related_name='flats', to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
